server:
  port: 7080
  
logging:
    path: /var/log/conan/console
    level:
        org.springframework: INFO
        org.spring.springboot.dao: DEBUG
        com.conan.console.server.mapper: DEBUG
conan:
  server:
    validate-url: http://120.79.152.124:8080/api/v1.0/sendValidationCode
    batch-template-file: batch_template.xlsx

minio:
  endpoint: http://120.79.197.22:9000
  ak: QUMQ3067MN3Y92L22BQJ
  sk: cpi/k6A5kk8hbOA+pT+LTIFs5/1p5hpNVl4Z28MJ
  backet-name: conan-server-2.0
    
datasource:
  master:
    jdbcUrl : jdbc:mysql://103.249.108.107:3306/tknDb2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false  
    username : root
    password : Apple1688!@#
    driver-class-name : com.mysql.jdbc.Driver
    max-idle : 10
    max-wait : 10000
    min-idle : 5
    initial-size : 5
    validation-query : SELECT 1
    test-on-borrow : false
    test-while-idle : true
    time-between-eviction-runs-millis : 18800
  slave:
    jdbcUrl : jdbc:mysql://103.249.108.107:3306/ptbrain?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false  
    username : root
    password : Apple1688!@#
    driver-class-name : com.mysql.jdbc.Driver
    max-idle : 10
    max-wait : 10000
    min-idle : 5
    initial-size : 5
    validation-query : SELECT 1
    test-on-borrow : false
    test-while-idle : true
    time-between-eviction-runs-millis : 18800    