server:
  port: 80

datasource:
  master:
    jdbcUrl : jdbc:mysql://120.79.197.22:3306/tknDb2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false  
    username : root
    password : Apple1688!@#
    driver-class-name : com.mysql.jdbc.Driver
    max-idle : 10
    max-wait : 10000
    min-idle : 5
    initial-size : 5
    validation-query : SELECT 1
    test-on-borrow : false
    test-while-idle : true
    time-between-eviction-runs-millis : 18800
  slave:
    jdbcUrl : jdbc:mysql://120.79.197.22:3306/ptbrain?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false  
    username : root
    password : Apple1688!@#
    driver-class-name : com.mysql.jdbc.Driver
    max-idle : 10
    max-wait : 10000
    min-idle : 5
    initial-size : 5
    validation-query : SELECT 1
    test-on-borrow : false
    test-while-idle : true
    time-between-eviction-runs-millis : 18800
    
logging:
    path: /var/log/conan/console
    level:
        org.springframework: INFO
        org.spring.springboot.dao: DEBUG
        com.conan.console.server.mapper: DEBUG
conan:
  server:
    validate-url: http://120.79.152.124:8080/api/v1.0/sendValidationCode