server:
  port: 7080

spring:
  datasource:
    url : jdbc:mysql://120.79.197.22:3306/tknDb2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false  
    username : root
    password : Apple1688!@#
    driverClassName : com.mysql.jdbc.Driver
    
logging:
    path: /var/log/conan/console
    level:
        org.springframework: INFO
        org.spring.springboot.dao: DEBUG
        com.conan.console.server.mapper: DEBUG
        

