package com.conan.console.server.mapper.slave;

import java.util.List;

import com.conan.console.server.entity.slave.FinalResult;

public interface FinalResultMapper {
	List<FinalResult> selectByPrimaryKeyList(List<String> nickHashList);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_result
     *
     * @mbg.generated Wed May 02 15:49:53 CST 2018
     */
    int deleteByPrimaryKey(String nick_hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_result
     *
     * @mbg.generated Wed May 02 15:49:53 CST 2018
     */
    int insert(FinalResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_result
     *
     * @mbg.generated Wed May 02 15:49:53 CST 2018
     */
    int insertSelective(FinalResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_result
     *
     * @mbg.generated Wed May 02 15:49:53 CST 2018
     */
    FinalResult selectByPrimaryKey(String nick_hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_result
     *
     * @mbg.generated Wed May 02 15:49:53 CST 2018
     */
    int updateByPrimaryKeySelective(FinalResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_result
     *
     * @mbg.generated Wed May 02 15:49:53 CST 2018
     */
    int updateByPrimaryKey(FinalResult record);
}