package com.conan.console.server.entity.master;

import java.util.Date;

public class GmDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_detail.detection_id
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    private String detection_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_detail.group_name
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    private String group_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_detail.group_comment
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    private String group_comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_detail.user_info_id
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    private String user_info_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_detail.id
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_detail.created_at
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_detail.updated_at
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    private Date updated_at;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_detail.detection_id
     *
     * @return the value of gm_detail.detection_id
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public String getDetection_id() {
        return detection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_detail.detection_id
     *
     * @param detection_id the value for gm_detail.detection_id
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public void setDetection_id(String detection_id) {
        this.detection_id = detection_id == null ? null : detection_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_detail.group_name
     *
     * @return the value of gm_detail.group_name
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public String getGroup_name() {
        return group_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_detail.group_name
     *
     * @param group_name the value for gm_detail.group_name
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public void setGroup_name(String group_name) {
        this.group_name = group_name == null ? null : group_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_detail.group_comment
     *
     * @return the value of gm_detail.group_comment
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public String getGroup_comment() {
        return group_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_detail.group_comment
     *
     * @param group_comment the value for gm_detail.group_comment
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public void setGroup_comment(String group_comment) {
        this.group_comment = group_comment == null ? null : group_comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_detail.user_info_id
     *
     * @return the value of gm_detail.user_info_id
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public String getUser_info_id() {
        return user_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_detail.user_info_id
     *
     * @param user_info_id the value for gm_detail.user_info_id
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public void setUser_info_id(String user_info_id) {
        this.user_info_id = user_info_id == null ? null : user_info_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_detail.id
     *
     * @return the value of gm_detail.id
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_detail.id
     *
     * @param id the value for gm_detail.id
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_detail.created_at
     *
     * @return the value of gm_detail.created_at
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_detail.created_at
     *
     * @param created_at the value for gm_detail.created_at
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_detail.updated_at
     *
     * @return the value of gm_detail.updated_at
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_detail.updated_at
     *
     * @param updated_at the value for gm_detail.updated_at
     *
     * @mbg.generated Thu Jun 28 02:58:50 CST 2018
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }
}