package com.conan.console.server.entity.master;

public class GroupMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.id
     *
     * @mbg.generated Wed Jun 27 11:27:54 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.group_id
     *
     * @mbg.generated Wed Jun 27 11:27:54 CST 2018
     */
    private String group_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.detection_id
     *
     * @mbg.generated Wed Jun 27 11:27:54 CST 2018
     */
    private String detection_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.id
     *
     * @return the value of group_member.id
     *
     * @mbg.generated Wed Jun 27 11:27:54 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.id
     *
     * @param id the value for group_member.id
     *
     * @mbg.generated Wed Jun 27 11:27:54 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.group_id
     *
     * @return the value of group_member.group_id
     *
     * @mbg.generated Wed Jun 27 11:27:54 CST 2018
     */
    public String getGroup_id() {
        return group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.group_id
     *
     * @param group_id the value for group_member.group_id
     *
     * @mbg.generated Wed Jun 27 11:27:54 CST 2018
     */
    public void setGroup_id(String group_id) {
        this.group_id = group_id == null ? null : group_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.detection_id
     *
     * @return the value of group_member.detection_id
     *
     * @mbg.generated Wed Jun 27 11:27:54 CST 2018
     */
    public String getDetection_id() {
        return detection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.detection_id
     *
     * @param detection_id the value for group_member.detection_id
     *
     * @mbg.generated Wed Jun 27 11:27:54 CST 2018
     */
    public void setDetection_id(String detection_id) {
        this.detection_id = detection_id == null ? null : detection_id.trim();
    }
}