package com.conan.console.server.entity.master;

import java.util.Date;

public class GroupDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.detection_account_id
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private String detection_account_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.created_at
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.account_name
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private String account_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.account_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double account_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.detail_score0
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double detail_score0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.detail_score1
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double detail_score1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.detail_score2
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double detail_score2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.detail_score3
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double detail_score3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.detail_score4
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double detail_score4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.register_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double register_info_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.identify_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double identify_info_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.background_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double background_info_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.trade_process_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double trade_process_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.trade_habit_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double trade_habit_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.logistics_character_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double logistics_character_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.account_history_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double account_history_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.activity_score0
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double activity_score0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.activity_score1
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double activity_score1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.activity_score2
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double activity_score2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.account_growup_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double account_growup_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.trade_frequency_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double trade_frequency_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.like_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private Double like_info_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.group_name
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private String group_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.group_comment
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private String group_comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.user_info_id
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private String user_info_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_detail.group_id
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    private String group_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.detection_account_id
     *
     * @return the value of group_detail.detection_account_id
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public String getDetection_account_id() {
        return detection_account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.detection_account_id
     *
     * @param detection_account_id the value for group_detail.detection_account_id
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setDetection_account_id(String detection_account_id) {
        this.detection_account_id = detection_account_id == null ? null : detection_account_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.created_at
     *
     * @return the value of group_detail.created_at
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.created_at
     *
     * @param created_at the value for group_detail.created_at
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.account_name
     *
     * @return the value of group_detail.account_name
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public String getAccount_name() {
        return account_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.account_name
     *
     * @param account_name the value for group_detail.account_name
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setAccount_name(String account_name) {
        this.account_name = account_name == null ? null : account_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.account_score
     *
     * @return the value of group_detail.account_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getAccount_score() {
        return account_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.account_score
     *
     * @param account_score the value for group_detail.account_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setAccount_score(Double account_score) {
        this.account_score = account_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.detail_score0
     *
     * @return the value of group_detail.detail_score0
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getDetail_score0() {
        return detail_score0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.detail_score0
     *
     * @param detail_score0 the value for group_detail.detail_score0
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setDetail_score0(Double detail_score0) {
        this.detail_score0 = detail_score0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.detail_score1
     *
     * @return the value of group_detail.detail_score1
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getDetail_score1() {
        return detail_score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.detail_score1
     *
     * @param detail_score1 the value for group_detail.detail_score1
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setDetail_score1(Double detail_score1) {
        this.detail_score1 = detail_score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.detail_score2
     *
     * @return the value of group_detail.detail_score2
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getDetail_score2() {
        return detail_score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.detail_score2
     *
     * @param detail_score2 the value for group_detail.detail_score2
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setDetail_score2(Double detail_score2) {
        this.detail_score2 = detail_score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.detail_score3
     *
     * @return the value of group_detail.detail_score3
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getDetail_score3() {
        return detail_score3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.detail_score3
     *
     * @param detail_score3 the value for group_detail.detail_score3
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setDetail_score3(Double detail_score3) {
        this.detail_score3 = detail_score3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.detail_score4
     *
     * @return the value of group_detail.detail_score4
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getDetail_score4() {
        return detail_score4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.detail_score4
     *
     * @param detail_score4 the value for group_detail.detail_score4
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setDetail_score4(Double detail_score4) {
        this.detail_score4 = detail_score4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.register_info_score
     *
     * @return the value of group_detail.register_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getRegister_info_score() {
        return register_info_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.register_info_score
     *
     * @param register_info_score the value for group_detail.register_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setRegister_info_score(Double register_info_score) {
        this.register_info_score = register_info_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.identify_info_score
     *
     * @return the value of group_detail.identify_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getIdentify_info_score() {
        return identify_info_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.identify_info_score
     *
     * @param identify_info_score the value for group_detail.identify_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setIdentify_info_score(Double identify_info_score) {
        this.identify_info_score = identify_info_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.background_info_score
     *
     * @return the value of group_detail.background_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getBackground_info_score() {
        return background_info_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.background_info_score
     *
     * @param background_info_score the value for group_detail.background_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setBackground_info_score(Double background_info_score) {
        this.background_info_score = background_info_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.trade_process_score
     *
     * @return the value of group_detail.trade_process_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getTrade_process_score() {
        return trade_process_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.trade_process_score
     *
     * @param trade_process_score the value for group_detail.trade_process_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setTrade_process_score(Double trade_process_score) {
        this.trade_process_score = trade_process_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.trade_habit_score
     *
     * @return the value of group_detail.trade_habit_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getTrade_habit_score() {
        return trade_habit_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.trade_habit_score
     *
     * @param trade_habit_score the value for group_detail.trade_habit_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setTrade_habit_score(Double trade_habit_score) {
        this.trade_habit_score = trade_habit_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.logistics_character_score
     *
     * @return the value of group_detail.logistics_character_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getLogistics_character_score() {
        return logistics_character_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.logistics_character_score
     *
     * @param logistics_character_score the value for group_detail.logistics_character_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setLogistics_character_score(Double logistics_character_score) {
        this.logistics_character_score = logistics_character_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.account_history_score
     *
     * @return the value of group_detail.account_history_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getAccount_history_score() {
        return account_history_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.account_history_score
     *
     * @param account_history_score the value for group_detail.account_history_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setAccount_history_score(Double account_history_score) {
        this.account_history_score = account_history_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.activity_score0
     *
     * @return the value of group_detail.activity_score0
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getActivity_score0() {
        return activity_score0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.activity_score0
     *
     * @param activity_score0 the value for group_detail.activity_score0
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setActivity_score0(Double activity_score0) {
        this.activity_score0 = activity_score0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.activity_score1
     *
     * @return the value of group_detail.activity_score1
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getActivity_score1() {
        return activity_score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.activity_score1
     *
     * @param activity_score1 the value for group_detail.activity_score1
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setActivity_score1(Double activity_score1) {
        this.activity_score1 = activity_score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.activity_score2
     *
     * @return the value of group_detail.activity_score2
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getActivity_score2() {
        return activity_score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.activity_score2
     *
     * @param activity_score2 the value for group_detail.activity_score2
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setActivity_score2(Double activity_score2) {
        this.activity_score2 = activity_score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.account_growup_score
     *
     * @return the value of group_detail.account_growup_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getAccount_growup_score() {
        return account_growup_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.account_growup_score
     *
     * @param account_growup_score the value for group_detail.account_growup_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setAccount_growup_score(Double account_growup_score) {
        this.account_growup_score = account_growup_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.trade_frequency_score
     *
     * @return the value of group_detail.trade_frequency_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getTrade_frequency_score() {
        return trade_frequency_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.trade_frequency_score
     *
     * @param trade_frequency_score the value for group_detail.trade_frequency_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setTrade_frequency_score(Double trade_frequency_score) {
        this.trade_frequency_score = trade_frequency_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.like_info_score
     *
     * @return the value of group_detail.like_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public Double getLike_info_score() {
        return like_info_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.like_info_score
     *
     * @param like_info_score the value for group_detail.like_info_score
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setLike_info_score(Double like_info_score) {
        this.like_info_score = like_info_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.group_name
     *
     * @return the value of group_detail.group_name
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public String getGroup_name() {
        return group_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.group_name
     *
     * @param group_name the value for group_detail.group_name
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setGroup_name(String group_name) {
        this.group_name = group_name == null ? null : group_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.group_comment
     *
     * @return the value of group_detail.group_comment
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public String getGroup_comment() {
        return group_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.group_comment
     *
     * @param group_comment the value for group_detail.group_comment
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setGroup_comment(String group_comment) {
        this.group_comment = group_comment == null ? null : group_comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.user_info_id
     *
     * @return the value of group_detail.user_info_id
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public String getUser_info_id() {
        return user_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.user_info_id
     *
     * @param user_info_id the value for group_detail.user_info_id
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setUser_info_id(String user_info_id) {
        this.user_info_id = user_info_id == null ? null : user_info_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_detail.group_id
     *
     * @return the value of group_detail.group_id
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public String getGroup_id() {
        return group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_detail.group_id
     *
     * @param group_id the value for group_detail.group_id
     *
     * @mbg.generated Wed Jun 27 20:14:23 CST 2018
     */
    public void setGroup_id(String group_id) {
        this.group_id = group_id == null ? null : group_id.trim();
    }
}