package com.conan.console.server.entity.master;

import java.util.Date;

public class RechargeBill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.id
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.created_at
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.updated_at
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private Date updated_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.recharge_type
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private String recharge_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.photo
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.comment
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.rmb_amount
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private Float rmb_amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.gold_amount
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private Float gold_amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.gold_coupon
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private Float gold_coupon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.gold_total
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private Float gold_total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.user_info_id
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private String user_info_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.verified_time
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private Date verified_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.success_time
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private Date success_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_bill.user_bill_id
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    private String user_bill_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.id
     *
     * @return the value of recharge_bill.id
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.id
     *
     * @param id the value for recharge_bill.id
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.created_at
     *
     * @return the value of recharge_bill.created_at
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.created_at
     *
     * @param created_at the value for recharge_bill.created_at
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.updated_at
     *
     * @return the value of recharge_bill.updated_at
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.updated_at
     *
     * @param updated_at the value for recharge_bill.updated_at
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.recharge_type
     *
     * @return the value of recharge_bill.recharge_type
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public String getRecharge_type() {
        return recharge_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.recharge_type
     *
     * @param recharge_type the value for recharge_bill.recharge_type
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setRecharge_type(String recharge_type) {
        this.recharge_type = recharge_type == null ? null : recharge_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.photo
     *
     * @return the value of recharge_bill.photo
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.photo
     *
     * @param photo the value for recharge_bill.photo
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.comment
     *
     * @return the value of recharge_bill.comment
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.comment
     *
     * @param comment the value for recharge_bill.comment
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.rmb_amount
     *
     * @return the value of recharge_bill.rmb_amount
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public Float getRmb_amount() {
        return rmb_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.rmb_amount
     *
     * @param rmb_amount the value for recharge_bill.rmb_amount
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setRmb_amount(Float rmb_amount) {
        this.rmb_amount = rmb_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.gold_amount
     *
     * @return the value of recharge_bill.gold_amount
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public Float getGold_amount() {
        return gold_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.gold_amount
     *
     * @param gold_amount the value for recharge_bill.gold_amount
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setGold_amount(Float gold_amount) {
        this.gold_amount = gold_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.gold_coupon
     *
     * @return the value of recharge_bill.gold_coupon
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public Float getGold_coupon() {
        return gold_coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.gold_coupon
     *
     * @param gold_coupon the value for recharge_bill.gold_coupon
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setGold_coupon(Float gold_coupon) {
        this.gold_coupon = gold_coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.gold_total
     *
     * @return the value of recharge_bill.gold_total
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public Float getGold_total() {
        return gold_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.gold_total
     *
     * @param gold_total the value for recharge_bill.gold_total
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setGold_total(Float gold_total) {
        this.gold_total = gold_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.user_info_id
     *
     * @return the value of recharge_bill.user_info_id
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public String getUser_info_id() {
        return user_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.user_info_id
     *
     * @param user_info_id the value for recharge_bill.user_info_id
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setUser_info_id(String user_info_id) {
        this.user_info_id = user_info_id == null ? null : user_info_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.verified_time
     *
     * @return the value of recharge_bill.verified_time
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public Date getVerified_time() {
        return verified_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.verified_time
     *
     * @param verified_time the value for recharge_bill.verified_time
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setVerified_time(Date verified_time) {
        this.verified_time = verified_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.success_time
     *
     * @return the value of recharge_bill.success_time
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public Date getSuccess_time() {
        return success_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.success_time
     *
     * @param success_time the value for recharge_bill.success_time
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setSuccess_time(Date success_time) {
        this.success_time = success_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_bill.user_bill_id
     *
     * @return the value of recharge_bill.user_bill_id
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public String getUser_bill_id() {
        return user_bill_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_bill.user_bill_id
     *
     * @param user_bill_id the value for recharge_bill.user_bill_id
     *
     * @mbg.generated Mon Apr 30 00:35:43 CST 2018
     */
    public void setUser_bill_id(String user_bill_id) {
        this.user_bill_id = user_bill_id == null ? null : user_bill_id.trim();
    }
}