package com.conan.console.server.entity.master;

import java.util.Date;

public class UserRemain{

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_remain.id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_remain.gold_amount
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private Double gold_amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_remain.gold_coupon
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private Double gold_coupon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_remain.user_info_id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private String user_info_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_remain.created_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_remain.updated_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private Date updated_at;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_remain.id
     *
     * @return the value of user_remain.id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_remain.id
     *
     * @param id the value for user_remain.id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_remain.gold_amount
     *
     * @return the value of user_remain.gold_amount
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public Double getGold_amount() {
        return gold_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_remain.gold_amount
     *
     * @param gold_amount the value for user_remain.gold_amount
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setGold_amount(Double gold_amount) {
        this.gold_amount = gold_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_remain.gold_coupon
     *
     * @return the value of user_remain.gold_coupon
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public Double getGold_coupon() {
        return gold_coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_remain.gold_coupon
     *
     * @param gold_coupon the value for user_remain.gold_coupon
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setGold_coupon(Double gold_coupon) {
        this.gold_coupon = gold_coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_remain.user_info_id
     *
     * @return the value of user_remain.user_info_id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public String getUser_info_id() {
        return user_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_remain.user_info_id
     *
     * @param user_info_id the value for user_remain.user_info_id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setUser_info_id(String user_info_id) {
        this.user_info_id = user_info_id == null ? null : user_info_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_remain.created_at
     *
     * @return the value of user_remain.created_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_remain.created_at
     *
     * @param created_at the value for user_remain.created_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_remain.updated_at
     *
     * @return the value of user_remain.updated_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_remain.updated_at
     *
     * @param updated_at the value for user_remain.updated_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }
}