package com.conan.console.server.mapper.master;

import com.conan.console.server.entity.master.CostRecord;

public interface CostRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int insert(CostRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int insertSelective(CostRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    CostRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int updateByPrimaryKeySelective(CostRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int updateByPrimaryKey(CostRecord record);
}