package com.conan.console.server.mapper.master;

import org.apache.ibatis.annotations.Param;

import com.conan.console.server.entity.master.CostRecord;

public interface CostRecordMapper {
	
	
	
	long singleScanUser(@Param("range_date_start") String range_date_start,@Param("range_date_end") String range_date_end);
	long singleScanRecords(@Param("range_date_start") String range_date_start,@Param("range_date_end") String range_date_end);
	
	long batchScanUser(@Param("range_date_start") String range_date_start,@Param("range_date_end") String range_date_end);
	long batchScanRecords(@Param("range_date_start") String range_date_start,@Param("range_date_end") String range_date_end);
	
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    CostRecord selectLastRecordByUserInfoId(String user_info_id);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int insert(CostRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int insertSelective(CostRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    CostRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int updateByPrimaryKeySelective(CostRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int updateByPrimaryKey(CostRecord record);
}