package com.conan.console.server.mapper.master;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.conan.console.server.entity.master.Group;

public interface GroupMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table group
	 *
	 * @mbg.generated Wed Jun 27 00:57:16 CST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table group
	 *
	 * @mbg.generated Wed Jun 27 00:57:16 CST 2018
	 */
	int insert(Group record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table group
	 *
	 * @mbg.generated Wed Jun 27 00:57:16 CST 2018
	 */
	int insertSelective(Group record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table group
	 *
	 * @mbg.generated Wed Jun 27 00:57:16 CST 2018
	 */
	List<Group> selectByUserInfoId(@Param("user_info_id") String user_info_id, @Param("pageNo") int pageNo,
			@Param("pageSize") int pageSize);
	
	int selectByUserInfoIdTotal(@Param("user_info_id") String user_info_id);

	Group selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table group
	 *
	 * @mbg.generated Wed Jun 27 00:57:16 CST 2018
	 */
	int updateByPrimaryKeySelective(Group record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table group
	 *
	 * @mbg.generated Wed Jun 27 00:57:16 CST 2018
	 */
	int updateByPrimaryKey(Group record);
}