package com.conan.console.server.mapper.master;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.conan.console.server.entity.master.UserInfo;
import com.conan.console.server.parameter.QueryUserListParameters;

public interface UserInfoMapper {
	
	UserInfo selectByPhoneNo(String phone_no);
	
	long selectTdRegisterCntTotal(@Param("td") Date td);
	long selectTdLoginCntTotal(@Param("td") Date td);
	long selectTtRegisteredCntTotal();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    UserInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int updateByPrimaryKey(UserInfo record);
    
    List<UserInfo> selectByQueryUserListParameters(
			@Param("queryUserListParameters") QueryUserListParameters queryUserListParameters, @Param("pageSize") int pageSize);

	int selectByQueryUserListParametersTotal(@Param("queryUserListParameters") QueryUserListParameters queryUserListParameters);
    
}