package com.conan.console.server.mapper.master;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.conan.console.server.entity.master.UserBill;
import com.conan.console.server.parameter.UserGetBillParameters;

public interface UserBillMapper {
	List<UserBill> selectByUserGetBillParameters(
			@Param("userGetBillParameters") UserGetBillParameters userGetBillParameters,
			@Param("user_info_id") String user_info_id, @Param("pageSize") int pageSize);

	int selectByUserGetBillParametersTotal(@Param("userGetBillParameters") UserGetBillParameters userGetBillParameters,
			@Param("user_info_id") String user_info_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_bill
	 *
	 * @mbg.generated Mon Apr 23 00:59:28 CST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_bill
	 *
	 * @mbg.generated Mon Apr 23 00:59:28 CST 2018
	 */
	int insert(UserBill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_bill
	 *
	 * @mbg.generated Mon Apr 23 00:59:28 CST 2018
	 */
	int insertSelective(UserBill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_bill
	 *
	 * @mbg.generated Mon Apr 23 00:59:28 CST 2018
	 */
	UserBill selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_bill
	 *
	 * @mbg.generated Mon Apr 23 00:59:28 CST 2018
	 */
	int updateByPrimaryKeySelective(UserBill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_bill
	 *
	 * @mbg.generated Mon Apr 23 00:59:28 CST 2018
	 */
	int updateByPrimaryKey(UserBill record);
}