package com.conan.console.server.mapper;

import com.conan.console.server.entity.CostRecord;

public interface CostRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int insert(CostRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int insertSelective(CostRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    CostRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int updateByPrimaryKeySelective(CostRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_record
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int updateByPrimaryKey(CostRecord record);
}