package com.conan.console.server.mapper;

import com.conan.console.server.entity.DetectionAccount;

public interface DetectionAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int insert(DetectionAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int insertSelective(DetectionAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    DetectionAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int updateByPrimaryKeySelective(DetectionAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int updateByPrimaryKey(DetectionAccount record);
}