package com.conan.console.server.mapper;

import com.conan.console.server.entity.DetectionAccount;

public interface DetectionAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int insert(DetectionAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int insertSelective(DetectionAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    DetectionAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int updateByPrimaryKeySelective(DetectionAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection_account
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int updateByPrimaryKey(DetectionAccount record);
}