package com.conan.console.server.mapper;

import com.conan.console.server.entity.UserRemain;

public interface UserRemainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int insert(UserRemain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int insertSelective(UserRemain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    UserRemain selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int updateByPrimaryKeySelective(UserRemain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    int updateByPrimaryKey(UserRemain record);
}