package com.conan.console.server.mapper;

import com.conan.console.server.entity.UserBill;

public interface UserBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int insert(UserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int insertSelective(UserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    UserBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int updateByPrimaryKeySelective(UserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int updateByPrimaryKey(UserBill record);
}