package com.conan.console.server.mapper;

import com.conan.console.server.entity.UserRemain;

public interface UserRemainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int insert(UserRemain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int insertSelective(UserRemain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    UserRemain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int updateByPrimaryKeySelective(UserRemain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_remain
     *
     * @mbg.generated Sun Apr 22 03:26:51 CST 2018
     */
    int updateByPrimaryKey(UserRemain record);
}