package com.conan.console.server.entity;

import java.util.Date;

public class UserAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_info_id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private String user_info_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.hashed_passwd
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private String hashed_passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.created_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.updated_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private Date updated_at;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.id
     *
     * @return the value of user_auth.id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.id
     *
     * @param id the value for user_auth.id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_info_id
     *
     * @return the value of user_auth.user_info_id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public String getUser_info_id() {
        return user_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_info_id
     *
     * @param user_info_id the value for user_auth.user_info_id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setUser_info_id(String user_info_id) {
        this.user_info_id = user_info_id == null ? null : user_info_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.hashed_passwd
     *
     * @return the value of user_auth.hashed_passwd
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public String getHashed_passwd() {
        return hashed_passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.hashed_passwd
     *
     * @param hashed_passwd the value for user_auth.hashed_passwd
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setHashed_passwd(String hashed_passwd) {
        this.hashed_passwd = hashed_passwd == null ? null : hashed_passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.created_at
     *
     * @return the value of user_auth.created_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.created_at
     *
     * @param created_at the value for user_auth.created_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.updated_at
     *
     * @return the value of user_auth.updated_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.updated_at
     *
     * @param updated_at the value for user_auth.updated_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }
}