package com.conan.console.server.entity;

import java.util.Date;

public class UserBill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bill.id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bill.created_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bill.bill_type
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private String bill_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bill.remain_gold
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private Float remain_gold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bill.bill_digest
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private String bill_digest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bill.bill_status
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private String bill_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bill.updated_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private Date updated_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bill.user_info_id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    private String user_info_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bill.id
     *
     * @return the value of user_bill.id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bill.id
     *
     * @param id the value for user_bill.id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bill.created_at
     *
     * @return the value of user_bill.created_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bill.created_at
     *
     * @param created_at the value for user_bill.created_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bill.bill_type
     *
     * @return the value of user_bill.bill_type
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public String getBill_type() {
        return bill_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bill.bill_type
     *
     * @param bill_type the value for user_bill.bill_type
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setBill_type(String bill_type) {
        this.bill_type = bill_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bill.remain_gold
     *
     * @return the value of user_bill.remain_gold
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public Float getRemain_gold() {
        return remain_gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bill.remain_gold
     *
     * @param remain_gold the value for user_bill.remain_gold
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setRemain_gold(Float remain_gold) {
        this.remain_gold = remain_gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bill.bill_digest
     *
     * @return the value of user_bill.bill_digest
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public String getBill_digest() {
        return bill_digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bill.bill_digest
     *
     * @param bill_digest the value for user_bill.bill_digest
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setBill_digest(String bill_digest) {
        this.bill_digest = bill_digest == null ? null : bill_digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bill.bill_status
     *
     * @return the value of user_bill.bill_status
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public String getBill_status() {
        return bill_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bill.bill_status
     *
     * @param bill_status the value for user_bill.bill_status
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setBill_status(String bill_status) {
        this.bill_status = bill_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bill.updated_at
     *
     * @return the value of user_bill.updated_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bill.updated_at
     *
     * @param updated_at the value for user_bill.updated_at
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bill.user_info_id
     *
     * @return the value of user_bill.user_info_id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public String getUser_info_id() {
        return user_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bill.user_info_id
     *
     * @param user_info_id the value for user_bill.user_info_id
     *
     * @mbg.generated Mon Apr 23 00:59:28 CST 2018
     */
    public void setUser_info_id(String user_info_id) {
        this.user_info_id = user_info_id == null ? null : user_info_id.trim();
    }
}